/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { randomBytes } from 'crypto';
import * as vscode from 'vscode';

const paths: Record<string, string> = {
	robot: 'M5 8h14v12H5z M9 12h.01 M15 12h.01 M9 16h6 M12 8V4 M10 4h4 M2 11v6 M22 11v6',
	dashboard: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
	drive: 'M12 3v18 M3 12h18 M8 7l4-4 4 4 M8 17l4 4 4-4 M7 8l-4 4 4 4 M17 8l4 4-4 4',
	camera: 'M3 7h4l2-3h6l2 3h4v13H3z M16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
	map: 'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2z M9 3v16 M15 5v16',
	navigation: 'M3 3l18 8-8 2-2 8z',
	sensors: 'M12 12l6-6 M21 12a9 9 0 1 1-9-9 M17 12a5 5 0 1 1-5-5',
	system: 'M3 4h18v14H3z M7 22h10 M12 18v4 M7 8l3 3-3 3 M13 14h4',
	settings: 'M4 6h16 M4 12h16 M4 18h16 M8 3v6 M16 9v6 M10 15v6',
	stop: 'M7 3h10l4 4v10l-4 4H7l-4-4V7z M9 9h6v6H9z'
};

function icon(name: string): string {
	return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.robot}"/></svg>`;
}
function escape(value: string): string { return value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', '\u0027': '&#39;' }[c]!)); }
function t(value: string): string { return escape(vscode.l10n.t(value)); }
function drive(): string {
	return `<div class="drive" aria-label="${t('Drive Control')}"><button data-drive="1,0" class="forward" data-online aria-label="${t('Forward')}">↑<small>${t('Forward')}</small></button><button data-drive="0,1" data-online aria-label="${t('Turn Left')}">←<small>${t('Left')}</small></button><button data-drive="0,0" data-online class="stop">■<small>${t('Stop')}</small></button><button data-drive="0,-1" data-online aria-label="${t('Turn Right')}">→<small>${t('Right')}</small></button><button data-drive="-1,0" class="backward" data-online aria-label="${t('Reverse')}">↓<small>${t('Reverse')}</small></button></div>`;
}

export function robotControlHtml(webview: vscode.Webview, extensionUri: vscode.Uri): string {
	const nonce = randomBytes(16).toString('base64');
	const asset = (name: string) => webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, 'media', name)).toString();
	const pages = [['dashboard', 'Dashboard', 'dashboard'], ['remote-control', 'Remote Control', 'drive'], ['camera', 'Camera', 'camera'], ['mapping', 'Mapping', 'map'], ['navigation', 'Navigation', 'navigation'], ['sensors', 'Sensors', 'sensors'], ['system', 'System', 'system'], ['settings', 'Settings', 'settings']];
	const field = (id: string, label: string, attrs = '') => `<label>${t(label)}<input id="${id}" ${attrs}></label>`;
	return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${webview.cspSource} data:; style-src ${webview.cspSource}; script-src 'nonce-${nonce}';">
<title>Redbrick Robot Control</title><link rel="stylesheet" href="${asset('robot-control.css')}"></head><body>
<header class="topbar"><div class="brand">${icon('robot')}<div>Redbrick <strong>Robot Control</strong><small>${t('ROS 2 • Humble / Jazzy')}</small></div></div><div class="connection"><span id="statusText" class="badge">${t('Disconnected')}</span><span id="endpoint" class="muted">${t('No Robot Selected')}</span><button data-page="settings">${icon('settings')}${t('Settings')}</button><button id="connect" class="primary" disabled>${t('Connect')}</button></div></header>
<nav class="tabs" aria-label="${t('Robot Control Pages')}">${pages.map(([id, label, glyph]) => `<button data-page="${id}" class="tab${id === 'dashboard' ? ' active' : ''}" aria-current="${id === 'dashboard' ? 'page' : 'false'}">${icon(glyph)}<span>${t(label)}</span></button>`).join('')}</nav>
<div id="notice" role="status" aria-live="polite">${t('Loading Robot Control…')}</div>
<main>
<section id="dashboard" class="page active"><div class="metrics"><article><span>${t('Connection')}</span><strong id="dashConnection">${t('Offline')}</strong><small id="dashIp">—</small></article><article><span>${t('Battery')}</span><strong id="battery">—</strong><small id="batteryVoltage">${t('Waiting for Sensor')}</small></article><article><span>CPU / RAM</span><strong id="resources">— / —</strong><small id="temperature">${t('Waiting for System Monitor')}</small></article><article><span>${t('Robot Status')}</span><strong id="robotStatus">${t('Not Connected')}</strong><small id="motion">0.00 m/s · 0.00 rad/s</small></article></div>
<div class="cockpit"><article class="card map-card"><div class="card-title"><h2>${icon('map')}${t('Live Map')}</h2><button data-page="navigation">${t('Navigation')} ↗</button></div><div class="visual"><canvas id="dashboardCanvas" aria-label="${t('Live Occupancy Map')}"></canvas><span class="map-empty placeholder">${t('Waiting for Map')}<small>${t('Connect and start your robot’s mapping or navigation nodes.')}</small></span></div><footer id="mapSummary">${t('No Map Received')}</footer></article><div class="cockpit-side"><article class="card"><div class="card-title"><h2>${icon('camera')}${t('Live Camera')}</h2><button data-page="camera">${t('Expand')} ↗</button></div><div class="camera-frame compact"><img id="dashboardCamera" alt="${t('Robot Camera')}" hidden><span class="camera-empty placeholder">${t('Waiting for Camera')}</span></div></article><article class="card"><h2>${icon('drive')}${t('Drive Control')}</h2>${drive()}<p class="muted">${t('Hold to move. Release to stop.')}</p><button data-page="remote-control">${t('Adjust Speed')} ↗</button></article></div></div></section>
<section id="remote-control" class="page"><div class="columns"><article class="card"><h2>${icon('drive')}${t('Drive Control')}</h2>${drive()}<p>${t('Hold a button, or use W/A/S/D and arrow keys. Release to stop.')}</p><p class="muted" id="motionTopic"></p></article><article class="card"><h2>${t('Speed Limits')}</h2><label>${t('Linear Speed')}<output id="linearValue">0.20 m/s</output><input id="linearSpeed" type="range" min="0" max="0.5" step="0.01" value="0.2"></label><label>${t('Angular Speed')}<output id="angularValue">0.60 rad/s</output><input id="angularSpeed" type="range" min="0" max="1.5" step="0.05" value="0.6"></label><p class="muted">${t('Maximum speeds and topic names can be changed in Settings.')}</p><button data-page="settings">${icon('settings')}${t('Robot Settings')}</button></article></div></section>
<section id="camera" class="page"><div class="toolbar"><h1>${icon('camera')}${t('Camera')}</h1><span id="cameraTopic" class="muted"></span><button id="cameraSnapshot" data-online>${t('Save Snapshot')}</button></div><div class="camera-frame"><img id="cameraImage" alt="${t('Robot Camera')}" hidden><span class="camera-empty placeholder">${t('Waiting for Compressed Camera Image')}</span></div></section>
<section id="mapping" class="page"><div class="toolbar"><h1>${icon('map')}${t('Mapping')}</h1><button id="startSlam" data-online>${t('Activate SLAM')}</button><button id="stopSlam" data-online>${t('Deactivate SLAM')}</button><input id="mapName" aria-label="${t('Map Name')}" value="redbrick_map"><button id="saveMap" data-online class="primary">${t('Save Map')}</button></div><p class="muted">${t('Requires a running, configured SLAM lifecycle node and Nav2 map saver.')}</p><div class="visual"><canvas id="mappingCanvas"></canvas><span class="map-empty placeholder">${t('Waiting for Map')}</span></div></section>
<section id="navigation" class="page"><div class="toolbar"><h1>${icon('navigation')}${t('Navigation')}</h1><button id="cancelNav" data-online>${t('Cancel Navigation')}</button><span id="navStatus" class="muted">${t('Click a free map cell to send a goal.')}</span></div><label class="inline">${t('Goal Heading (Degrees)')}<input id="goalYaw" type="number" value="0" min="-180" max="180"></label><div class="visual"><canvas id="navigationCanvas" aria-label="${t('Click Map to Navigate')}"></canvas><span class="map-empty placeholder">${t('Waiting for Map')}</span></div></section>
<section id="sensors" class="page"><div class="toolbar"><h1>${icon('sensors')}${t('Sensors')}</h1><button id="refreshGraph" data-online>${t('Refresh ROS Graph')}</button><span id="scanStatus" class="muted">${t('Waiting for LiDAR')}</span></div><div class="columns"><div class="visual"><canvas id="lidarCanvas"></canvas></div><article class="card"><h2>${t('Sensor Status')}</h2><div id="sensorList" class="list"></div><h2>${t('ROS 2 Nodes')}</h2><div id="nodeList" class="list"></div><h2>${t('ROS 2 Topics')}</h2><div id="topicList" class="list"></div></article></div></section>
<section id="system" class="page"><div class="toolbar"><h1>${icon('system')}${t('System & Logs')}</h1><span id="rosDistro" class="muted">ROS 2</span><button id="exportSetup">${t('Export Robot Setup Package')}</button></div><p id="systemProfile" class="muted"></p><div class="toolbar"><label class="inline">${t('Log Level')}<select id="logLevel"><option value="all">${t('All')}</option><option value="error">${t('Error')}</option><option value="warn">${t('Warning')}</option><option value="info">${t('Info')}</option></select></label><button id="clearLog">${t('Clear')}</button><button id="exportLog">${t('Export Log')}</button></div><pre id="terminal" class="terminal" aria-label="${t('ROS 2 Logs')}"></pre></section>
<section id="settings" class="page"><div class="toolbar"><h1>${icon('settings')}${t('Robot Settings')}</h1><span class="muted">${t('Saved on this computer. Disconnect before editing.')}</span></div><form id="settingsForm"><div class="toolbar form-actions"><button id="saveSettings" class="primary" type="submit">${t('Save Settings')}</button><button id="testConnection" type="button">${t('Test Connection')}</button><button type="button" id="resetProfile">${t('Restore Profile Defaults')}</button></div><fieldset id="settingsFields"><div class="columns"><article class="card"><h2>${t('Connection')}</h2>${field('host', 'Robot IP / Hostname', 'placeholder="192.168.1.100" required')}${field('port', 'WebSocket Port', 'type="number" min="1" max="65535" value="9090" required')}<label>${t('Robot Profile')}<select id="profile"></select></label><label class="inline"><input id="secure" type="checkbox">${t('Use Secure WebSocket (WSS)')}</label><p class="muted">${t('Run rosbridge on the robot and use the same Wi-Fi or LAN.')}</p></article><article class="card"><h2>${t('Motion & Frames')}</h2>${field('limitLinear', 'Maximum Linear Speed (m/s)', 'type="number" min="0.01" max="2" step="0.01" required')}${field('limitAngular', 'Maximum Angular Speed (rad/s)', 'type="number" min="0.01" max="4" step="0.01" required')}${field('mapFrame', 'Map Frame', 'required')}<p class="muted">${t('The robot base must also stop on command timeout. Software stop requires a working network.')}</p></article></div><article class="card"><h2>${t('ROS Topics & Services')}</h2><p class="muted">${t('Use your robot’s topic names. Camera must publish CompressedImage; motion uses Twist.')}</p><div id="topicSettings" class="settings-grid"></div></article></fieldset></form><div id="testResult" role="status" class="card muted">${t('Connection test checks rosbridge and reports available topics and services.')}</div></section>
</main><footer class="safety-bar"><span id="safetyState">${t('Motion Requires a Live Connection')}</span><button id="releaseEstop" disabled>${t('Reset Stop')}</button><button id="emergencyStop" class="danger">${icon('stop')}${t('Emergency Stop')}</button></footer>
<script nonce="${nonce}" src="${asset('robot-control.js')}"></script></body></html>`;
}
